# Generated by Django 5.0.6 on 2024-05-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created'], 'verbose_name': 'formacion', 'verbose_name_plural': 'formaciones'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created'], 'verbose_name': 'conocimiento', 'verbose_name_plural': 'conocimientos'},
        ),
    ]
